# Generated by Django 3.1.7 on 2021-03-05 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('surname', models.CharField(max_length=63)),
                ('middlename', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=127)),
                ('city', models.CharField(max_length=127)),
                ('uni', models.CharField(max_length=127)),
                ('course', models.CharField(max_length=127)),
                ('with_topic', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=511)),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conference')),
            ],
        ),
    ]
