# Generated by Django 3.1.7 on 2021-03-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
